# Generated by Django 2.2.6 on 2019-11-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20191122_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='animalvacunado',
            options={'verbose_name': 'Animal vacunado', 'verbose_name_plural': 'Animales vacunados'},
        ),
        migrations.AlterModelOptions(
            name='caravana',
            options={'verbose_name': 'Caravana', 'verbose_name_plural': 'Caravanas'},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={'verbose_name': 'Vacuna', 'verbose_name_plural': 'Vacunas'},
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.CharField(default='Bovino', help_text='Bovino - Vacuno - Ovino - Porcino', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(help_text='Se autocompleta a partir de la fecha indicada como nacimiento', verbose_name='Edad en dias'),
        ),
    ]
