# Generated by Django 2.2.6 on 2019-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20191128_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tipo',
            field=models.CharField(default='Bovino', help_text='Bovino - Ovino - Porcino', max_length=100),
        ),
    ]
