# Generated by Django 2.2.6 on 2019-12-10 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20191128_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(default=1, help_text='Se autocompleta a partir de la fecha indicada como nacimiento', verbose_name='Edad en dias'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fecha_nac',
            field=models.DateField(default=datetime.date.today, help_text='Ingrese la fecha de nacimiento', verbose_name='Fecha de nacimiento'),
        ),
    ]
