# Generated by Django 2.2.6 on 2019-12-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20191210_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravana',
            name='color',
            field=models.CharField(default='Azul', help_text='Ingrese el color de la caravana', max_length=100, verbose_name='Color'),
        ),
    ]
