# Generated by Django 2.2.6 on 2019-12-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20191210_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravana',
            name='CUIG',
            field=models.CharField(help_text='La obtención de la Clave Única de Identificación Ganadera (CUIG) es un requisito indispensable para adquirir las nuevas caravanas, que identificarán a los animales en forma individual.', max_length=100),
        ),
        migrations.AlterField(
            model_name='caravana',
            name='RENSPA',
            field=models.CharField(help_text='El RENSPA es un registro obligatorio para todas las actividades de producción primaria del sector agrario. El responsable sanitario de la actividad debe aclarar sus datos personales, los del establecimiento y los datos de la explotación.', max_length=100),
        ),
    ]
