# Generated by Django 3.0.8 on 2020-07-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20191226_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='caravana_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.Caravana'),
        ),
    ]
