# Generated by Django 3.0.8 on 2020-07-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vincular', '0001_initial'),
        ('animals', '0009_auto_20200728_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravana',
            name='codRFID',
            field=models.OneToOneField(help_text='Seleccione el codigo de RFID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vincular.RFID'),
        ),
    ]
