# Generated by Django 3.0.8 on 2020-07-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20200729_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='caravana_id',
            new_name='caravana',
        ),
    ]
