# Generated by Django 3.0.8 on 2020-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(default=0, help_text='Codigo de Chip', verbose_name='Codigo de Chip')),
            ],
            options={
                'verbose_name': 'RFID',
                'verbose_name_plural': 'RFIDs',
                'ordering': ['-id'],
            },
        ),
    ]
